app/models.py
from . import db
from mylog import time_print
import random


class Post(db.Model):
    __tablename__ = 'posts'
    id = db.Column(db.Integer, primary_key=True)
    url_num = db.Column(db.Integer)
    title = db.Column(db.String(10))
    img = db.Column(db.String(64))
    content = db.Column(db.String())
    timestamp = db.Column(db.String, default=time_print())
    comments = db.relationship('Comment', backref='post', lazy='dynamic')

    def save(self):
        db.session.add(self)
        db.session.commit()


class Comment(db.Model):
    __tablename__ = 'comments'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(10), default='游客')
    img = db.Column(db.String(64))
    content = db.Column(db.String())
    timestamp = db.Column(db.String, default=time_print())
    reply_id = db.Column(db.Integer, default=0)
    post_id = db.Column(db.Integer, db.ForeignKey('posts.id'))


    def __init__(self, content):
        self.content = content
        # self.img = '/static/img/' + str(random.randint(1,3)) + '.jpg'
        self.img = '/static/img/1.jpg'


    def save(self):
        db.session.add(self)
        db.session.commit()

    def json(self):
        extra = dict(
            post_id = self.post_id,
        )
        d = {k: v for k, v in self.__dict__.items() if k not in self.blacklist()}
        d.update(extra)
        return d

    def blacklist(self):
        b = [
            '_sa_instance_state',
        ]
        return b

    def get_replys(self):
        replys = Comment.query.filter_by(reply_id=self.id).all()
        for reply in replys:
            yield reply.json()

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

def init_app():
    db_path = 'db.sqlite'

    app = Flask(__name__)

    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = True
    app.config['SQLALCHEMY_DATABASE_URI'] = \
        'sqlite:///{}'.format(db_path)

    app.secret_key = 'a random string'

    db.init_app(app)
    db.app = app

    from .api import api as api_blueprint
    from .main import main as main_blueprint

    app.register_blueprint(api_blueprint)
    app.register_blueprint(main_blueprint)

    return app

app/api/__init__.py
from flask import Blueprint

api = Blueprint('api', __name__)

from . import views

app/api/views.py
from flask import request
from flask import jsonify

from mylog import log
from . import api
from ..models import Post
from ..models import Comment


@api.route('/posts/search', methods=['POST'])
def post_search():
    form = request.get_json()
    title = form.get('title', '')
    post = Post.query.filter_by(title=title).first()
    response = dict(
        success=False,
    )

    if len(title) != 0:
        d = dict(
            success=True,
            post_id=post.id,
        )
        response.update(d)
    elif len(title) == 0:
        response['message'] = '用户没输入数据！'
    elif post is None:
        response['message'] = '数据库没有用户查找的数据！'
    log('/post/search response: ', response)
    return jsonify(response)


@api.route('/comments/edit/<post_id>', methods=['POST'])
def comment_edit(post_id):
    post = Post.query.get_or_404(post_id)
    form = request.get_json()
    content = form.get('comment', '')
    response = dict(
        success=False,
    )

    if len(content) != 0:
        c = Comment(content)
        c.post = post
        c.save()
        log('评论发表成功')
        d = dict(
            success=True,
            data=c.json(),
        )
        response.update(d)
    else:
        response['message'] = '用户没输入数据！'
    log('/comment/edit response: ', response)
    return jsonify(response)
    #return redirect(url_for('post_view', post_id=post_id))


@api.route('/comments/reply/<comment_id>', methods=['POST'])
def reply(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    form = request.get_json()
    content = form.get('comment', '')
    response = dict(
        success=False,
    )

    if len(content) != 0:
        c = Comment(content)
        c.post = comment.post
        c.reply_id = comment_id
        c.save()
        log('评论发表成功')
        d = dict(
            success=True,
            data=c.json(),
        )
        response.update(d)
    else:
        response['message'] = '用户没输入数据！'
    log('/comment/edit response: ', response)
    return jsonify(response)

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/main/views.py
from flask import render_template
from flask import request
from ..models import Post

from . import main
PER_PAGE_NUMS = 3

@main.route('/')
def index_view():
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.order_by(Post.title.desc()).paginate(
        page,
        per_page=PER_PAGE_NUMS,
        error_out=False
    )
    posts = pagination.items
    return render_template('index.html',
                           posts=posts,
                           pagination=pagination)


@main.route('/posts/<post_id>')
def post_view(post_id):
    post = Post.query.get_or_404(post_id)
    pagination = Post.query.order_by(Post.title.desc()).filter(
        Post.title<=post.title).paginate(
        page=1,
        per_page=PER_PAGE_NUMS)
    return render_template('post.html',
                           post=post,
                           pagination=pagination)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">

    <title>{% block title %}{% endblock %} - [One · 一个]</title>


    <!-- Bootstrap Core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="/static/css/blog-home.css" rel="stylesheet">


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="/static/js/js/html5shiv.js"></script>
    <script src="/static/js/js/respond.min.js"></script>
    <![endif]-->
    <!-- jQuery -->
    <script src="/static/js/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="/static/js/js/bootstrap.min.js"></script>
    <script src="/static/js/api.js"></script>
    {% block head %}
    {% endblock %}
</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            {% block navbar %}
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{url_for('main.index_view')}}">主页</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="#"></a>
                    </li>
                    <li>
                        <a href="#"></a>
                    </li>
                    <li>
                        <a href="#"></a>
                    </li>
                </ul>
            </div>
            {% endblock %}
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>


    {% block content %}
    <!-- Page Content -->
    <div class="container">

        <div class="row">
            {% block blog_content %}
            <!-- Blog Entries Column -->
            <div class="col-md-8">
                {% block page_header %}
                <h1 class="page-header">

                    <small>复杂世界里, 一个就够了. One is all.</small>
                </h1>
                {% endblock %}

                {% block blog %}
                <!-- First Blog Post -->
                <h2>
                    <a href="#">Blog Post Title</a>
                </h2>
                <p class="lead">
                    by <a href="index.php">Start Bootstrap</a>
                </p>
                <p><span class="glyphicon glyphicon-time"></span> Posted on August 28, 2013 at 10:00 PM</p>
                <hr>
                <img class="img-responsive"
                     src="http://image.wufazhuce.com/Fl-sa5YvYbTbgmmEsKBuN-RPOoYX" alt="">
                <hr>
                <div class="well">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate, voluptates, voluptas
                    dolore ipsam cumque quam veniam accusantium laudantium adipisci architecto itaque dicta aperiam
                    maiores provident id incidunt autem. Magni, ratione.</p>
                </div>
                <a class="btn btn-primary" href="#">Read More <span class="glyphicon glyphicon-chevron-right"></span></a>

                <hr>

                <!-- Second Blog Post -->
                <h2>
                    <a href="#">Blog Post Title</a>
                </h2>
                <p class="lead">
                    by <a href="index.php">Start Bootstrap</a>
                </p>
                <p><span class="glyphicon glyphicon-time"></span> Posted on August 28, 2013 at 10:45 PM</p>
                <hr>
                <img class="img-responsive"
                     src="http://image.wufazhuce.com/FhIcL0Y1L_a10m4HjDmggPIRMzU3" alt="">
                <hr>
                <div class="well">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate, voluptates, voluptas
                    dolore ipsam cumque quam veniam accusantium laudantium adipisci architecto itaque dicta aperiam
                    maiores provident id incidunt autem. Magni, ratione.</p>
                </div>
                <a class="btn btn-primary" href="#">Read More <span class="glyphicon glyphicon-chevron-right"></span></a>


                <hr>


                <!-- Third Blog Post -->
                <h2>
                    <a href="#">Blog Post Title</a>
                </h2>
                <p class="lead">
                    by <a href="index.php">Start Bootstrap</a>
                </p>
                <p><span class="glyphicon glyphicon-time"></span> Posted on August 28, 2013 at 10:45 PM</p>
                <hr>
                <img class="img-responsive"
                     src="http://image.wufazhuce.com/Fuu2to_U8SiI2vdzAaSeAr4tH7UV" alt="">
                <hr>
                <div class="well">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate, voluptates, voluptas
                    dolore ipsam cumque quam veniam accusantium laudantium adipisci architecto itaque dicta aperiam
                    maiores provident id incidunt autem. Magni, ratione.</p>
                </div>
                <a class="btn btn-primary" href="#">Read More <span class="glyphicon glyphicon-chevron-right"></span></a>
                {% endblock %}

                <hr>

                {% block pager %}
                <!-- Pager -->
                <ul class="pager">
                    <li class="previous">
                        <a href="#">&larr; Older</a>
                    </li>
                    <li class="next">
                        <a href="#">Newer &rarr;</a>
                    </li>
                </ul>
                {% endblock %}

            </div>
            {% endblock %}

            {% block sidebar_content %}
            <!-- Blog Sidebar Widgets Column -->
            <div class="col-md-4">

                <!-- Blog Search Well -->
                <div class="well">
                    <h4>Blog Search</h4>
                    <div class="input-group">
                        <input type="text" class="form-control">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <span class="glyphicon glyphicon-search"></span>
                        </button>
                        </span>
                    </div>
                    <!-- /.input-group -->
                </div>
                {% block post_title %}
                <!-- Blog Categories Well -->
                <div class="well">
                    <h4>Blog Categories</h4>
                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                            </ul>
                        </div>
                        <!-- /.col-lg-6 -->
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                            </ul>
                        </div>
                        <!-- /.col-lg-6 -->
                    </div>
                    <!-- /.row -->
                </div>
                {% endblock %}

                <!-- Side Widget Well -->
                <div class="well">
                    <h4>Side Widget Well</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
                </div>

            </div>
            {% endblock %}
        </div>
        <!-- /.row -->

        <hr>
        {% block advert%}
        <!-- Footer -->

        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p></p>
                </div><!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </footer>
    {% endblock %}

    </div>
    <!-- /.container -->
    {% endblock %}

    {% block scripts %}



    {% endblock %}
</body>

</html>

app/templates/index.html
{% extends "base.html" %}

{% block head %}
    <script src="/static/js/search.js"></script>
    <script>
        var bindSearchActions = function() {
            $('#id-button-post-search').on('click', function(){
                searchPost();
            });
        };

        var __main = function() {
            bindSearchActions();
        };

        $(document).ready(function() {
            __main();
        });
    </script>

{% endblock %}

{% block blog %}
{% for post in posts %}
    <h2>
        <a href="/posts/{{ post.id }}">{{ post.title }}</a>
    </h2>
    <p><span class="glyphicon glyphicon-time"></span>{{ post.timestamp }}</p>
    <hr>
    <img class="img-responsive"
         src="{{ post.img }}" alt="">
    <hr>
    <div class="well">
        <p>{{ post.content }}</p>
    </div>
    <hr>
{% endfor %}
{% endblock %}

{% block pager %}
<!-- Pager -->
<ul class="pager">
    <li class="previous">
        <a href="{% if pagination.has_prev %}
                {{ url_for('main.index_view', page=pagination.page-1)}}
                {% else %}#
                {% endif %}">&larr; Older</a>
    </li>
    <li class="next">
        <a href="{% if pagination.has_next %}
                {{ url_for('main.index_view', page=pagination.page+1)}}
                {% else %}#
                {% endif %}">Newer &rarr;</a>
    </li>
</ul>
{% endblock %}

{% block sidebar_content %}
    <div class="col-md-4">
        <!-- Blog Search Well -->
        <div class="well">
            <h4>查找文章</h4>
            <div class="input-group">
                <input id="id-input-search" class="form-control" name="title" placeholder="{{posts[0].title}}">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="button" id="id-button-post-search">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                </span>
            </div>
            <!-- /.input-group -->
        </div>
        <!-- Blog Categories Well -->
        <div class="well">
            <h4>文章列表</h4>
            <div class="row">
                <div class="col-lg-7">
                    <ul class="list-unstyled">
                        {% for post in posts %}
                            <li><a href="/posts/{{post.id}}">{{ post.title }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <!-- /.col-lg-6 -->
                <div class="col-lg-5">
                    <ul class="list-unstyled">
                        {% for post in pagination.next().items %}
                            <li><a href="/posts/{{post.id}}">{{ post.title }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <!-- /.col-lg-6 -->
            </div>
            <!-- /.row -->
        </div>


        <!-- Side Widget Well -->
        <div class="well">
            <h4>广告位</h4>
            <p>如果你想打广告</p>
            <p>如果我想接广告</p>
            <p>请联系我~~~~~~~~~~</p>
        </div>

    </div>
{% endblock %}

app/templates/post.html
{% extends "index.html" %}
{% block title %}{{ post.title }}{% endblock %}

{% block head %}
    <script src="/static/js/comment.js"></script>
    <script src="/static/js/reply.js"></script>
    <script src="/static/js/search.js"></script>
    <script>
        var bindSearchActions = function() {
            $('#id-button-post-search').on('click', function(){
                searchPost();
            });
        };

        var bindAddActions = function() {
            $('#id-button-comment-add').on('click', function(){
                addNewComment();
            });
        };

        var bindReplyActions = function() {
            $('#id-button-reply-add').on('click', function(){
                addNewReply();
            });
        };

        var __main = function() {
            bindSearchActions();
            bindAddActions();
            bindReplyActions();

        };

        $(document).ready(function() {
            __main();
        });
    </script>

{% endblock %}

{% block blog_content %}
<!-- Blog Post Content Column -->
<div class="col-lg-8">
    <!-- Blog Post -->
    <!-- Title -->
    <h1>{{ post.title }}</h1>
    <hr>
    <!-- Date/Time -->
    <p><span class="glyphicon glyphicon-time"></span> {{ post.timestamp }}</p>
    <hr>
    <!-- Preview Image -->
    <img class="img-responsive" src="{{ post.img }}" alt="">
    <hr>
    <!-- Post Content -->
    <div class="well"  id="ct1">
        <p>{{ post.content }}</p>
    </div >
    <hr>
    <!-- Blog Comments -->
    <!-- Comments Form -->
    <div class="well">
        <h4>评论：</h4>
        <form role="form">
            <div class="form-group">
                <textarea class="form-control" id="id-textarea-comment" rows="3"></textarea>
            </div>
            <button type="button" class="btn btn-primary" id="id-button-comment-add">提交</button>
            <button type="button" class="btn btn-success" id="id-button-reply-add">回复</button>
        </form>
    </div>
    <hr>
    <!-- Posted Comments -->
    <!-- Comment -->

    <div id="id-div-comments" data-id="{{post.id}}">
        {% for comment in post.comments.all() %}
            {% if comment.reply_id == 0 %}
                <div class="media" id="id-div-add" data-id="{{post.id}}">
                    <a class="pull-left" href="#">
                        <img class="media-object" src="{{ comment.img }}"
                             width="80" height="80" alt="">
                    </a>
                    <div class="media-body">
                        <h4 class="media-heading">{{comment.username}}
                            <small>{{ comment.timestamp }}</small>
                        </h4>
                        {{comment.content}}
                        <div class="post-footer">
                            <a href="?id={{comment.id}}#ct1">
                                <span class="label label-success" id="id-span-reply">回复</span>
                            </a>
                        </div>
                        {% for reply in comment.get_replys() %}
                            <div class="media">
                                <a class="pull-left" href="#">
                                    <img class="media-object" src="{{ reply.img }}"
                                         width="80" height="80" alt="">
                                </a>
                                <div class="media-body">
                                    <h4 class="media-heading">{{reply.username}}
                                        <small>{{ reply.timestamp }}</small>
                                    </h4>
                                    {{reply.content}}
                                </div>
                            </div>
                        {% endfor %}
                        <div id="id-div-reply-add-{{comment.id}}"></div>
                    </div>
                </div>
                <hr>
            {% endif %}
        {% endfor %}
    </div>
</div>
{% endblock %}

{% block sidebar_content %}
    <div class="col-md-4">

        <!-- Blog Search Well -->
        <div class="well">
            <h4>查找文章</h4>
            <div class="input-group">
                <input id="id-input-search" class="form-control" name="title" placeholder="{{ post.title }}">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="button" id="id-button-post-search">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                </span>
            </div>
            <!-- /.input-group -->
        </div>
        <!-- Blog Categories Well -->
        <div class="well">
            <h4>文章列表</h4>
            <div class="row">
                <div class="col-lg-7">
                    <ul class="list-unstyled">
                        {% for p in pagination.items %}
                            <li><a href="/posts/{{p.id}}">{{ p.title }}</a></li>
                        {% endfor %}

                    </ul>
                </div>
                <!-- /.col-lg-6 -->
                <div class="col-lg-5">
                    <ul class="list-unstyled">
                        {% for p in pagination.next().items %}
                            <li><a href="/posts/{{p.id}}">{{ p.title }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <!-- /.col-lg-6 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- Side Widget Well -->
        <div class="well">
            <h4>广告位</h4>
            <p>如果你想打广告</p>
            <p>如果我想接广告</p>
            <p>请联系我~~~~~~~~~~</p>
        </div>

    </div>
{% endblock %}

app/templates/test.html
{% extends "base.html" %}
{% block title %}Test{% endblock %}

{% block navbar %}
    <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Test</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="#">test</a>
                    </li>
                    <li>
                        <a href="#">test</a>
                    </li>
                    <li>
                        <a href="#">test</a>
                    </li>
                </ul>
            </div>
{% endblock %}

{% block blog_content %}
<!-- Page Content -->
    <div class="container">

        <div class="row">

            <!-- Blog Post Content Column -->
            <div class="col-lg-8">

                <!-- Blog Post -->

                <!-- Title -->
                <h1>Blog Post Title</h1>

                <!-- Author -->
                <p class="lead">
                    by <a href="#">Start Bootstrap</a>
                </p>

                <hr>

                <!-- Date/Time -->
                <p><span class="glyphicon glyphicon-time"></span> Posted on August 24, 2013 at 9:00 PM</p>

                <hr>

                <!-- Preview Image -->
                <img class="img-responsive" src="http://placehold.it/900x300" alt="">

                <hr>

                <!-- Post Content -->
                <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, vero, obcaecati, aut, error quam sapiente nemo saepe quibusdam sit excepturi nam quia corporis eligendi eos magni recusandae laborum minus inventore?</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, doloribus, dolorem iusto blanditiis unde eius illum consequuntur neque dicta incidunt ullam ea hic porro optio ratione repellat perspiciatis. Enim, iure!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, nostrum, aliquid, animi, ut quas placeat totam sunt tempora commodi nihil ullam alias modi dicta saepe minima ab quo voluptatem obcaecati?</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, dolor quis. Sunt, ut, explicabo, aliquam tenetur ratione tempore quidem voluptates cupiditate voluptas illo saepe quaerat numquam recusandae? Qui, necessitatibus, est!</p>

                <hr>

                <!-- Blog Comments -->

                <!-- Comments Form -->
                <div class="well">
                    <h4>Leave a Comment:</h4>
                    <form role="form">
                        <div class="form-group">
                            <textarea class="form-control" rows="3"></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>

                <hr>

                <!-- Posted Comments -->

                <!-- Comment -->
                <div class="media">
                    <a class="pull-left" href="#">
                        <img class="media-object" src="http://placehold.it/64x64" alt="">
                    </a>
                    <div class="media-body">
                        <h4 class="media-heading">Start Bootstrap
                            <small>August 25, 2014 at 9:30 PM</small>
                        </h4>
                        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                    </div>
                </div>

                <!-- Comment -->
                <div class="media">
                    <a class="pull-left" href="#">
                        <img class="media-object" src="http://placehold.it/64x64" alt="">
                    </a>
                    <div class="media-body">
                        <h4 class="media-heading">Start Bootstrap
                            <small>August 25, 2014 at 9:30 PM</small>
                        </h4>
                        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                        <!-- Nested Comment -->
                        <div class="media">
                            <a class="pull-left" href="#">
                                <img class="media-object" src="http://placehold.it/64x64" alt="">
                            </a>
                            <div class="media-body">
                                <h4 class="media-heading">Nested Start Bootstrap
                                    <small>August 25, 2014 at 9:30 PM</small>
                                </h4>
                                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                            </div>
                        </div>
                        <!-- End Nested Comment -->
                    </div>
                </div>

            </div>
{% endblock %}